    
info:
  profile: prod
  
  
name: Paul and me
words: 'God bless you and me !!'

food: '{cipher}527d18faca8bb2afe27dd4911d436dcda2e4c9bc798a8eb6314cf7b17a6edf3c'

text: '{cipher}AQCP7enfeL1Uh02rR/lk7HHdPQQFH8qiFaQlXi9X/6tXVI1so1kWPS1yLgIHBcI7vnPJWy0jyVMoe6AcEdaPpdsVfdzBiDzOYbkJUSHFhsv8CodoVVKFcO4n/8pIcI2hP0QSAA8uxagwi84aLWsx19zWYqxvF+eqc8Gb5qCVlbN1ikkqU9q2Q2m35gL992CSk2FM78Dqh70Bz3thF0zKswwSnsSTkKa5CI2g/+A19USyJOKYTWyKtcoq1Cb/tVZwTW2Gof2+oYfav74hoTNnLbY4DHT+jsdz6PSyawvLWmcR9I/VGITrZFTtdjOAjlNCmWxPGkgPrOGhRbVSOk32Q/cJlX1q18J9zkfhOsgdkDaLyn0ANSpGjmRQqesD1qR8z78kYU/zMdaKwV/OokY2ugZ8'
